spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reactBoard
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  #JPA
  jpa:
    show-sql: true      #hibernate가 만들어준 SQL을 로그에서 보려면 true로 설정
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true        # 로그, 콘솔의 SQL을 좀 더 이쁘게 출력 배포할때는false로
        use_sql_comments: true  #sql 내부에 주석을 추가해준다.
        highlight_sql: true     #sql에 색을 입혀줌.
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create
